{
 "title": "PaperTrl-Dashboard-Primary-All",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Testing Root-Used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Testing All-Node\",device=\"/dev/nvme0n1p1\"}*100) / node_filesystem_size_bytes{job=\"Testing All-Node\",device=\"/dev/nvme0n1p1\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Testing Papertrl-used",
   "type": "stat",
   "description": "Used root FS",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"Testing All-Node\",device=\"/dev/mapper/LVMVolGroup--papertrl-papertrl\"} * 100) / node_filesystem_size_bytes{job=\"Testing All-Node\",device=\"/dev/mapper/LVMVolGroup--papertrl-papertrl\"})\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Testing DB-Used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Testing All-Node\",device=\"/dev/mapper/LVMVolGroup--db-db\"}*100) / node_filesystem_size_bytes{job=\"Testing All-Node\",device=\"/dev/mapper/LVMVolGroup--db-db\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Testing sftp-used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Testing All-Node\",device=\"/dev/mapper/LVMVolGroup--sftp-sftp\"}*100) / node_filesystem_size_bytes{job=\"Testing All-Node\",device=\"/dev/mapper/LVMVolGroup--sftp-sftp\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Testing databackups",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Testing All-Node\",device=\"/dev/mapper/LVMVolGroup--databackup-databackup\"}*100) / node_filesystem_size_bytes{job=\"Testing All-Node\",device=\"/dev/mapper/LVMVolGroup--databackup-databackup\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Testing Ram Usage",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"Testing All-Node\"} * 100) / node_memory_MemTotal_bytes{job=\"Testing All-Node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Testing CPU Usage",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"Testing All-Node\",mode=\"idle\"}[1m])) * 100)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Testing All-Node\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Papertrl - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Testing All-Node\",mountpoint=\"/papertrl\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Testing All-Node\",mountpoint=\"/papertrl/data/db\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SFTP - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Testing All-Node\",mountpoint=\"/papertrl/data/sftp\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DataBackup - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Testing All-Node\",mountpoint=\"/papertrl/backups/databackup\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"Testing All-Node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"Testing All-Node\"} - node_boot_time_seconds{job=\"Testing All-Node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QA Root-Used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"QA All-Node\",device=\"/dev/nvme0n1p1\"}*100) / node_filesystem_size_bytes{job=\"QA All-Node\",device=\"/dev/nvme0n1p1\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QA Papertrl-used",
   "type": "stat",
   "description": "Used root FS",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"QA All-Node\",device=\"/dev/mapper/LVMVolGroup--papertrl-papertrl\"} * 100) / node_filesystem_size_bytes{job=\"QA All-Node\",device=\"/dev/mapper/LVMVolGroup--papertrl-papertrl\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QA DB used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"QA All-Node\",device=\"/dev/mapper/LVMVolGroup--db-db\"}*100) / node_filesystem_size_bytes{job=\"QA All-Node\",device=\"/dev/mapper/LVMVolGroup--db-db\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QA sftp-used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"QA All-Node\",device=\"/dev/mapper/LVMVolGroup--sftp-sftp\"}*100) / node_filesystem_size_bytes{job=\"QA All-Node\",device=\"/dev/mapper/LVMVolGroup--sftp-sftp\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QA databackups",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"QA All-Node\",device=\"/dev/mapper/LVMVolGroup--databackup-databackup\"}*100) / node_filesystem_size_bytes{job=\"QA All-Node\",device=\"/dev/mapper/LVMVolGroup--databackup-databackup\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QA Ram Usage",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"QA All-Node\"} * 100) / node_memory_MemTotal_bytes{job=\"QA All-Node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QA-CPU Usage",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"QA All-Node\",mode=\"idle\"}[1m])) * 100)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"QA All-Node\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Papertrl - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"QA All-Node\",mountpoint=\"/papertrl\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"QA All-Node\",mountpoint=\"/papertrl/data/db\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SFTP - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"QA All-Node\",mountpoint=\"/papertrl/data/sftp\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DataBackup - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"QA All-Node\",mountpoint=\"/papertrl/backups/databackup\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"QA All-Node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"QA All-Node\"} - node_boot_time_seconds{job=\"QA All-Node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Demo Root-Used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Demo All-Node\",device=\"/dev/nvme0n1p1\"}*100) / node_filesystem_size_bytes{job=\"Demo All-Node\",device=\"/dev/nvme0n1p1\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Demo Papertrl-used",
   "type": "stat",
   "description": "Used root FS",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"Demo All-Node\",device=\"/dev/mapper/LVMVolGroup--papertrl-papertrl\"} * 100) / node_filesystem_size_bytes{job=\"Demo All-Node\",device=\"/dev/mapper/LVMVolGroup--papertrl-papertrl\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Demo DB used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Demo All-Node\",device=\"/dev/mapper/LVMVolGroup--db-db\"}*100) / node_filesystem_size_bytes{job=\"Demo All-Node\",device=\"/dev/mapper/LVMVolGroup--db-db\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Demo sftp-used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Demo All-Node\",device=\"/dev/mapper/LVMVolGroup--sftp-sftp\"}*100) / node_filesystem_size_bytes{job=\"Demo All-Node\",device=\"/dev/mapper/LVMVolGroup--sftp-sftp\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Demo sftp-used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Demo All-Node\",device=\"/dev/mapper/LVMVolGroup--databackup-databackup\"}*100) / node_filesystem_size_bytes{job=\"Demo All-Node\",device=\"/dev/mapper/LVMVolGroup--databackup-databackup\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Demo Ram Usage",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"Demo All-Node\"} * 100) / node_memory_MemTotal_bytes{job=\"Demo All-Node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Demo CPU Usage",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"Demo All-Node\",mode=\"idle\"}[1m])) * 100)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Demo All-Node\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Papertrl - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Demo All-Node\",mountpoint=\"/papertrl\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Demo All-Node\",mountpoint=\"/papertrl/data/db\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SFTP - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Demo All-Node\",mountpoint=\"/papertrl/data/sftp\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BackupData - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Demo All-Node\",mountpoint=\"/papertrl/backups/databackup\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"Demo All-Node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"Demo All-Node\"} - node_boot_time_seconds{job=\"Demo All-Node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prod Root-Used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Prod_3 All-Node\",device=\"/dev/nvme0n1p1\"}*100) / node_filesystem_size_bytes{job=\"Prod_3 All-Node\",device=\"/dev/nvme0n1p1\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prod Papertrl-used",
   "type": "stat",
   "description": "Used root FS",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"Prod_3 All-Node\",device=\"/dev/mapper/LVMVolGroup--papertrl-papertrl\"} * 100) / node_filesystem_size_bytes{job=\"Prod_3 All-Node\",device=\"/dev/mapper/LVMVolGroup--papertrl-papertrl\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prod DB used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Prod_3 All-Node\",device=\"/dev/mapper/LVMVolGroup--db-db\"}*100) / node_filesystem_size_bytes{job=\"Prod_3 All-Node\",device=\"/dev/mapper/LVMVolGroup--db-db\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prod sftp-used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Prod_3 All-Node\",device=\"/dev/mapper/LVMVolGroup--sftp-sftp\"}*100) / node_filesystem_size_bytes{job=\"Prod_3 All-Node\",device=\"/dev/mapper/LVMVolGroup--sftp-sftp\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BackupData-used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 -((node_filesystem_avail_bytes{job=\"Prod_3 All-Node\",device=\"/dev/mapper/LVMVolGroup--databackup-databackup\"}*100) / node_filesystem_size_bytes{job=\"Prod_3 All-Node\",device=\"/dev/mapper/LVMVolGroup--databackup-databackup\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prod Ram Usage",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"Prod_3 All-Node\"} * 100) / node_memory_MemTotal_bytes{job=\"Prod_3 All-Node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prod CPU Usage",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"Prod_3 All-Node\",mode=\"idle\"}[1m])) * 100)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Prod_3 All-Node\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Papertrl - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Prod_3 All-Node\",mountpoint=\"/papertrl\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Prod_3 All-Node\",mountpoint=\"/papertrl/data/db\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SFTP - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Prod_3 All-Node\",mountpoint=\"/papertrl/data/sftp\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BackupData - Total",
   "type": "stat",
   "description": "Total /papertrl FS",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"Prod_3 All-Node\",mountpoint=\"/papertrl/backups/databackup\",fstype!=\"rootfs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"Prod_3 All-Node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"Prod_3 All-Node\"} - node_boot_time_seconds{job=\"Prod_3 All-Node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Staging Ram Usage",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"Staging All-Node\"} * 100) / node_memory_MemTotal_bytes{job=\"Staging All-Node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Staging-CPU Usage",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"Staging All-Node\",mode=\"idle\"}[1m])) * 100)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_success{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{collector}} - Scrape success"
      },
      {
       "expr": "node_textfile_scrape_error{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{collector}} - Scrape textfile error (1 = true)"
      }
     ]
    }
   ]
  }
 ]
}